import type { CountryCode } from "libphonenumber-js";

/**
 * Static ISO 3166-1 alpha-2 country list with English and Romanian names.
 *
 * Hard-coded on purpose: `Intl.DisplayNames` output varies with the ICU data
 * shipped by the runtime (browser, Node, jsdom), which made option labels — and
 * therefore search results and tests — environment-dependent. Regenerate by
 * hand if a territory changes name.
 */
export interface CountryEntry {
  readonly code: CountryCode;
  readonly names: {
    readonly en: string;
    readonly ro: string;
  };
}

export type CountryNameLocale = keyof CountryEntry["names"];

export const COUNTRIES = [
  { code: "AC", names: { en: "Ascension Island", ro: "Insula Ascension" } },
  { code: "AD", names: { en: "Andorra", ro: "Andorra" } },
  {
    code: "AE",
    names: { en: "United Arab Emirates", ro: "Emiratele Arabe Unite" },
  },
  { code: "AF", names: { en: "Afghanistan", ro: "Afganistan" } },
  { code: "AG", names: { en: "Antigua & Barbuda", ro: "Antigua și Barbuda" } },
  { code: "AI", names: { en: "Anguilla", ro: "Anguilla" } },
  { code: "AL", names: { en: "Albania", ro: "Albania" } },
  { code: "AM", names: { en: "Armenia", ro: "Armenia" } },
  { code: "AO", names: { en: "Angola", ro: "Angola" } },
  { code: "AR", names: { en: "Argentina", ro: "Argentina" } },
  { code: "AS", names: { en: "American Samoa", ro: "Samoa Americană" } },
  { code: "AT", names: { en: "Austria", ro: "Austria" } },
  { code: "AU", names: { en: "Australia", ro: "Australia" } },
  { code: "AW", names: { en: "Aruba", ro: "Aruba" } },
  { code: "AX", names: { en: "Åland Islands", ro: "Insulele Åland" } },
  { code: "AZ", names: { en: "Azerbaijan", ro: "Azerbaidjan" } },
  {
    code: "BA",
    names: { en: "Bosnia & Herzegovina", ro: "Bosnia și Herțegovina" },
  },
  { code: "BB", names: { en: "Barbados", ro: "Barbados" } },
  { code: "BD", names: { en: "Bangladesh", ro: "Bangladesh" } },
  { code: "BE", names: { en: "Belgium", ro: "Belgia" } },
  { code: "BF", names: { en: "Burkina Faso", ro: "Burkina Faso" } },
  { code: "BG", names: { en: "Bulgaria", ro: "Bulgaria" } },
  { code: "BH", names: { en: "Bahrain", ro: "Bahrain" } },
  { code: "BI", names: { en: "Burundi", ro: "Burundi" } },
  { code: "BJ", names: { en: "Benin", ro: "Benin" } },
  { code: "BL", names: { en: "St. Barthélemy", ro: "Saint-Barthélemy" } },
  { code: "BM", names: { en: "Bermuda", ro: "Bermuda" } },
  { code: "BN", names: { en: "Brunei", ro: "Brunei" } },
  { code: "BO", names: { en: "Bolivia", ro: "Bolivia" } },
  {
    code: "BQ",
    names: { en: "Caribbean Netherlands", ro: "Insulele Caraibe Olandeze" },
  },
  { code: "BR", names: { en: "Brazil", ro: "Brazilia" } },
  { code: "BS", names: { en: "Bahamas", ro: "Bahamas" } },
  { code: "BT", names: { en: "Bhutan", ro: "Bhutan" } },
  { code: "BW", names: { en: "Botswana", ro: "Botswana" } },
  { code: "BY", names: { en: "Belarus", ro: "Belarus" } },
  { code: "BZ", names: { en: "Belize", ro: "Belize" } },
  { code: "CA", names: { en: "Canada", ro: "Canada" } },
  {
    code: "CC",
    names: { en: "Cocos (Keeling) Islands", ro: "Insulele Cocos (Keeling)" },
  },
  { code: "CD", names: { en: "Congo - Kinshasa", ro: "Congo - Kinshasa" } },
  {
    code: "CF",
    names: { en: "Central African Republic", ro: "Republica Centrafricană" },
  },
  {
    code: "CG",
    names: { en: "Congo - Brazzaville", ro: "Congo - Brazzaville" },
  },
  { code: "CH", names: { en: "Switzerland", ro: "Elveția" } },
  { code: "CI", names: { en: "Côte d’Ivoire", ro: "Côte d’Ivoire" } },
  { code: "CK", names: { en: "Cook Islands", ro: "Insulele Cook" } },
  { code: "CL", names: { en: "Chile", ro: "Chile" } },
  { code: "CM", names: { en: "Cameroon", ro: "Camerun" } },
  { code: "CN", names: { en: "China", ro: "China" } },
  { code: "CO", names: { en: "Colombia", ro: "Columbia" } },
  { code: "CR", names: { en: "Costa Rica", ro: "Costa Rica" } },
  { code: "CU", names: { en: "Cuba", ro: "Cuba" } },
  { code: "CV", names: { en: "Cape Verde", ro: "Capul Verde" } },
  { code: "CW", names: { en: "Curaçao", ro: "Curaçao" } },
  { code: "CX", names: { en: "Christmas Island", ro: "Insula Christmas" } },
  { code: "CY", names: { en: "Cyprus", ro: "Cipru" } },
  { code: "CZ", names: { en: "Czechia", ro: "Cehia" } },
  { code: "DE", names: { en: "Germany", ro: "Germania" } },
  { code: "DJ", names: { en: "Djibouti", ro: "Djibouti" } },
  { code: "DK", names: { en: "Denmark", ro: "Danemarca" } },
  { code: "DM", names: { en: "Dominica", ro: "Dominica" } },
  {
    code: "DO",
    names: { en: "Dominican Republic", ro: "Republica Dominicană" },
  },
  { code: "DZ", names: { en: "Algeria", ro: "Algeria" } },
  { code: "EC", names: { en: "Ecuador", ro: "Ecuador" } },
  { code: "EE", names: { en: "Estonia", ro: "Estonia" } },
  { code: "EG", names: { en: "Egypt", ro: "Egipt" } },
  { code: "EH", names: { en: "Western Sahara", ro: "Sahara Occidentală" } },
  { code: "ER", names: { en: "Eritrea", ro: "Eritreea" } },
  { code: "ES", names: { en: "Spain", ro: "Spania" } },
  { code: "ET", names: { en: "Ethiopia", ro: "Etiopia" } },
  { code: "FI", names: { en: "Finland", ro: "Finlanda" } },
  { code: "FJ", names: { en: "Fiji", ro: "Fiji" } },
  { code: "FK", names: { en: "Falkland Islands", ro: "Insulele Falkland" } },
  { code: "FM", names: { en: "Micronesia", ro: "Micronezia" } },
  { code: "FO", names: { en: "Faroe Islands", ro: "Insulele Feroe" } },
  { code: "FR", names: { en: "France", ro: "Franța" } },
  { code: "GA", names: { en: "Gabon", ro: "Gabon" } },
  { code: "GB", names: { en: "United Kingdom", ro: "Regatul Unit" } },
  { code: "GD", names: { en: "Grenada", ro: "Grenada" } },
  { code: "GE", names: { en: "Georgia", ro: "Georgia" } },
  { code: "GF", names: { en: "French Guiana", ro: "Guyana Franceză" } },
  { code: "GG", names: { en: "Guernsey", ro: "Guernsey" } },
  { code: "GH", names: { en: "Ghana", ro: "Ghana" } },
  { code: "GI", names: { en: "Gibraltar", ro: "Gibraltar" } },
  { code: "GL", names: { en: "Greenland", ro: "Groenlanda" } },
  { code: "GM", names: { en: "Gambia", ro: "Gambia" } },
  { code: "GN", names: { en: "Guinea", ro: "Guineea" } },
  { code: "GP", names: { en: "Guadeloupe", ro: "Guadelupa" } },
  { code: "GQ", names: { en: "Equatorial Guinea", ro: "Guineea Ecuatorială" } },
  { code: "GR", names: { en: "Greece", ro: "Grecia" } },
  { code: "GT", names: { en: "Guatemala", ro: "Guatemala" } },
  { code: "GU", names: { en: "Guam", ro: "Guam" } },
  { code: "GW", names: { en: "Guinea-Bissau", ro: "Guineea-Bissau" } },
  { code: "GY", names: { en: "Guyana", ro: "Guyana" } },
  {
    code: "HK",
    names: { en: "Hong Kong SAR China", ro: "R.A.S. Hong Kong, China" },
  },
  { code: "HN", names: { en: "Honduras", ro: "Honduras" } },
  { code: "HR", names: { en: "Croatia", ro: "Croația" } },
  { code: "HT", names: { en: "Haiti", ro: "Haiti" } },
  { code: "HU", names: { en: "Hungary", ro: "Ungaria" } },
  { code: "ID", names: { en: "Indonesia", ro: "Indonezia" } },
  { code: "IE", names: { en: "Ireland", ro: "Irlanda" } },
  { code: "IL", names: { en: "Israel", ro: "Israel" } },
  { code: "IM", names: { en: "Isle of Man", ro: "Insula Man" } },
  { code: "IN", names: { en: "India", ro: "India" } },
  {
    code: "IO",
    names: {
      en: "British Indian Ocean Territory",
      ro: "Teritoriul Britanic din Oceanul Indian",
    },
  },
  { code: "IQ", names: { en: "Iraq", ro: "Irak" } },
  { code: "IR", names: { en: "Iran", ro: "Iran" } },
  { code: "IS", names: { en: "Iceland", ro: "Islanda" } },
  { code: "IT", names: { en: "Italy", ro: "Italia" } },
  { code: "JE", names: { en: "Jersey", ro: "Jersey" } },
  { code: "JM", names: { en: "Jamaica", ro: "Jamaica" } },
  { code: "JO", names: { en: "Jordan", ro: "Iordania" } },
  { code: "JP", names: { en: "Japan", ro: "Japonia" } },
  { code: "KE", names: { en: "Kenya", ro: "Kenya" } },
  { code: "KG", names: { en: "Kyrgyzstan", ro: "Kârgâzstan" } },
  { code: "KH", names: { en: "Cambodia", ro: "Cambodgia" } },
  { code: "KI", names: { en: "Kiribati", ro: "Kiribati" } },
  { code: "KM", names: { en: "Comoros", ro: "Comore" } },
  {
    code: "KN",
    names: { en: "St. Kitts & Nevis", ro: "Saint Kitts și Nevis" },
  },
  { code: "KP", names: { en: "North Korea", ro: "Coreea de Nord" } },
  { code: "KR", names: { en: "South Korea", ro: "Coreea de Sud" } },
  { code: "KW", names: { en: "Kuwait", ro: "Kuweit" } },
  { code: "KY", names: { en: "Cayman Islands", ro: "Insulele Cayman" } },
  { code: "KZ", names: { en: "Kazakhstan", ro: "Kazahstan" } },
  { code: "LA", names: { en: "Laos", ro: "Laos" } },
  { code: "LB", names: { en: "Lebanon", ro: "Liban" } },
  { code: "LC", names: { en: "St. Lucia", ro: "Sfânta Lucia" } },
  { code: "LI", names: { en: "Liechtenstein", ro: "Liechtenstein" } },
  { code: "LK", names: { en: "Sri Lanka", ro: "Sri Lanka" } },
  { code: "LR", names: { en: "Liberia", ro: "Liberia" } },
  { code: "LS", names: { en: "Lesotho", ro: "Lesotho" } },
  { code: "LT", names: { en: "Lithuania", ro: "Lituania" } },
  { code: "LU", names: { en: "Luxembourg", ro: "Luxemburg" } },
  { code: "LV", names: { en: "Latvia", ro: "Letonia" } },
  { code: "LY", names: { en: "Libya", ro: "Libia" } },
  { code: "MA", names: { en: "Morocco", ro: "Maroc" } },
  { code: "MC", names: { en: "Monaco", ro: "Monaco" } },
  { code: "MD", names: { en: "Moldova", ro: "Republica Moldova" } },
  { code: "ME", names: { en: "Montenegro", ro: "Muntenegru" } },
  { code: "MF", names: { en: "St. Martin", ro: "Sfântul Martin" } },
  { code: "MG", names: { en: "Madagascar", ro: "Madagascar" } },
  { code: "MH", names: { en: "Marshall Islands", ro: "Insulele Marshall" } },
  { code: "MK", names: { en: "North Macedonia", ro: "Macedonia de Nord" } },
  { code: "ML", names: { en: "Mali", ro: "Mali" } },
  { code: "MM", names: { en: "Myanmar (Burma)", ro: "Myanmar (Birmania)" } },
  { code: "MN", names: { en: "Mongolia", ro: "Mongolia" } },
  { code: "MO", names: { en: "Macao SAR China", ro: "R.A.S. Macao, China" } },
  {
    code: "MP",
    names: { en: "Northern Mariana Islands", ro: "Insulele Mariane de Nord" },
  },
  { code: "MQ", names: { en: "Martinique", ro: "Martinica" } },
  { code: "MR", names: { en: "Mauritania", ro: "Mauritania" } },
  { code: "MS", names: { en: "Montserrat", ro: "Montserrat" } },
  { code: "MT", names: { en: "Malta", ro: "Malta" } },
  { code: "MU", names: { en: "Mauritius", ro: "Mauritius" } },
  { code: "MV", names: { en: "Maldives", ro: "Maldive" } },
  { code: "MW", names: { en: "Malawi", ro: "Malawi" } },
  { code: "MX", names: { en: "Mexico", ro: "Mexic" } },
  { code: "MY", names: { en: "Malaysia", ro: "Malaysia" } },
  { code: "MZ", names: { en: "Mozambique", ro: "Mozambic" } },
  { code: "NA", names: { en: "Namibia", ro: "Namibia" } },
  { code: "NC", names: { en: "New Caledonia", ro: "Noua Caledonie" } },
  { code: "NE", names: { en: "Niger", ro: "Niger" } },
  { code: "NF", names: { en: "Norfolk Island", ro: "Insula Norfolk" } },
  { code: "NG", names: { en: "Nigeria", ro: "Nigeria" } },
  { code: "NI", names: { en: "Nicaragua", ro: "Nicaragua" } },
  { code: "NL", names: { en: "Netherlands", ro: "Țările de Jos" } },
  { code: "NO", names: { en: "Norway", ro: "Norvegia" } },
  { code: "NP", names: { en: "Nepal", ro: "Nepal" } },
  { code: "NR", names: { en: "Nauru", ro: "Nauru" } },
  { code: "NU", names: { en: "Niue", ro: "Niue" } },
  { code: "NZ", names: { en: "New Zealand", ro: "Noua Zeelandă" } },
  { code: "OM", names: { en: "Oman", ro: "Oman" } },
  { code: "PA", names: { en: "Panama", ro: "Panama" } },
  { code: "PE", names: { en: "Peru", ro: "Peru" } },
  { code: "PF", names: { en: "French Polynesia", ro: "Polinezia Franceză" } },
  { code: "PG", names: { en: "Papua New Guinea", ro: "Papua-Noua Guinee" } },
  { code: "PH", names: { en: "Philippines", ro: "Filipine" } },
  { code: "PK", names: { en: "Pakistan", ro: "Pakistan" } },
  { code: "PL", names: { en: "Poland", ro: "Polonia" } },
  {
    code: "PM",
    names: { en: "St. Pierre & Miquelon", ro: "Saint-Pierre și Miquelon" },
  },
  { code: "PR", names: { en: "Puerto Rico", ro: "Puerto Rico" } },
  {
    code: "PS",
    names: { en: "Palestinian Territories", ro: "Teritoriile Palestiniene" },
  },
  { code: "PT", names: { en: "Portugal", ro: "Portugalia" } },
  { code: "PW", names: { en: "Palau", ro: "Palau" } },
  { code: "PY", names: { en: "Paraguay", ro: "Paraguay" } },
  { code: "QA", names: { en: "Qatar", ro: "Qatar" } },
  { code: "RE", names: { en: "Réunion", ro: "Réunion" } },
  { code: "RO", names: { en: "Romania", ro: "România" } },
  { code: "RS", names: { en: "Serbia", ro: "Serbia" } },
  { code: "RU", names: { en: "Russia", ro: "Rusia" } },
  { code: "RW", names: { en: "Rwanda", ro: "Rwanda" } },
  { code: "SA", names: { en: "Saudi Arabia", ro: "Arabia Saudită" } },
  { code: "SB", names: { en: "Solomon Islands", ro: "Insulele Solomon" } },
  { code: "SC", names: { en: "Seychelles", ro: "Seychelles" } },
  { code: "SD", names: { en: "Sudan", ro: "Sudan" } },
  { code: "SE", names: { en: "Sweden", ro: "Suedia" } },
  { code: "SG", names: { en: "Singapore", ro: "Singapore" } },
  { code: "SH", names: { en: "St. Helena", ro: "Sfânta Elena" } },
  { code: "SI", names: { en: "Slovenia", ro: "Slovenia" } },
  {
    code: "SJ",
    names: { en: "Svalbard & Jan Mayen", ro: "Svalbard și Jan Mayen" },
  },
  { code: "SK", names: { en: "Slovakia", ro: "Slovacia" } },
  { code: "SL", names: { en: "Sierra Leone", ro: "Sierra Leone" } },
  { code: "SM", names: { en: "San Marino", ro: "San Marino" } },
  { code: "SN", names: { en: "Senegal", ro: "Senegal" } },
  { code: "SO", names: { en: "Somalia", ro: "Somalia" } },
  { code: "SR", names: { en: "Suriname", ro: "Suriname" } },
  { code: "SS", names: { en: "South Sudan", ro: "Sudanul de Sud" } },
  {
    code: "ST",
    names: { en: "São Tomé & Príncipe", ro: "São Tomé și Príncipe" },
  },
  { code: "SV", names: { en: "El Salvador", ro: "El Salvador" } },
  { code: "SX", names: { en: "Sint Maarten", ro: "Sint-Maarten" } },
  { code: "SY", names: { en: "Syria", ro: "Siria" } },
  { code: "SZ", names: { en: "Eswatini", ro: "Eswatini" } },
  { code: "TA", names: { en: "Tristan da Cunha", ro: "Tristan da Cunha" } },
  {
    code: "TC",
    names: { en: "Turks & Caicos Islands", ro: "Insulele Turks și Caicos" },
  },
  { code: "TD", names: { en: "Chad", ro: "Ciad" } },
  { code: "TG", names: { en: "Togo", ro: "Togo" } },
  { code: "TH", names: { en: "Thailand", ro: "Thailanda" } },
  { code: "TJ", names: { en: "Tajikistan", ro: "Tadjikistan" } },
  { code: "TK", names: { en: "Tokelau", ro: "Tokelau" } },
  { code: "TL", names: { en: "Timor-Leste", ro: "Timor-Leste" } },
  { code: "TM", names: { en: "Turkmenistan", ro: "Turkmenistan" } },
  { code: "TN", names: { en: "Tunisia", ro: "Tunisia" } },
  { code: "TO", names: { en: "Tonga", ro: "Tonga" } },
  { code: "TR", names: { en: "Türkiye", ro: "Turcia" } },
  { code: "TT", names: { en: "Trinidad & Tobago", ro: "Trinidad și Tobago" } },
  { code: "TV", names: { en: "Tuvalu", ro: "Tuvalu" } },
  { code: "TW", names: { en: "Taiwan", ro: "Taiwan" } },
  { code: "TZ", names: { en: "Tanzania", ro: "Tanzania" } },
  { code: "UA", names: { en: "Ukraine", ro: "Ucraina" } },
  { code: "UG", names: { en: "Uganda", ro: "Uganda" } },
  {
    code: "US",
    names: { en: "United States", ro: "Statele Unite ale Americii" },
  },
  { code: "UY", names: { en: "Uruguay", ro: "Uruguay" } },
  { code: "UZ", names: { en: "Uzbekistan", ro: "Uzbekistan" } },
  {
    code: "VA",
    names: { en: "Vatican City", ro: "Statul Cetății Vaticanului" },
  },
  {
    code: "VC",
    names: {
      en: "St. Vincent & Grenadines",
      ro: "Saint Vincent și Grenadinele",
    },
  },
  { code: "VE", names: { en: "Venezuela", ro: "Venezuela" } },
  {
    code: "VG",
    names: { en: "British Virgin Islands", ro: "Insulele Virgine Britanice" },
  },
  {
    code: "VI",
    names: { en: "U.S. Virgin Islands", ro: "Insulele Virgine Americane" },
  },
  { code: "VN", names: { en: "Vietnam", ro: "Vietnam" } },
  { code: "VU", names: { en: "Vanuatu", ro: "Vanuatu" } },
  { code: "WF", names: { en: "Wallis & Futuna", ro: "Wallis și Futuna" } },
  { code: "WS", names: { en: "Samoa", ro: "Samoa" } },
  { code: "XK", names: { en: "Kosovo", ro: "Kosovo" } },
  { code: "YE", names: { en: "Yemen", ro: "Yemen" } },
  { code: "YT", names: { en: "Mayotte", ro: "Mayotte" } },
  { code: "ZA", names: { en: "South Africa", ro: "Africa de Sud" } },
  { code: "ZM", names: { en: "Zambia", ro: "Zambia" } },
  { code: "ZW", names: { en: "Zimbabwe", ro: "Zimbabwe" } },
] as const satisfies readonly CountryEntry[];

const DEFAULT_NAME_LOCALE = "en" satisfies CountryNameLocale;

const countriesByCode = new Map<string, CountryEntry>(
  COUNTRIES.map((country) => [country.code, country]),
);

/** Resolves a BCP 47 tag (`ro-RO`, `en`) to a locale we have names for. */
export function resolveCountryNameLocale(
  locale: string | undefined,
): CountryNameLocale {
  const language = locale?.split("-")[0]?.toLowerCase();

  return language === "ro" ? "ro" : DEFAULT_NAME_LOCALE;
}

export function findCountry(code: string | null | undefined) {
  return code == null ? undefined : countriesByCode.get(code.toUpperCase());
}

export function getCountryName(
  code: string | null | undefined,
  locale?: string,
): string | undefined {
  return findCountry(code)?.names[resolveCountryNameLocale(locale)];
}
