import type { Metadata } from "next";
import { Geist_Mono, Manrope } from "next/font/google";
import { cookies } from "next/headers";
import { TooltipProvider } from "@repo/ui/components/tooltip";
import { AppShell } from "../components/AppShell";
import { SessionProvider } from "../components/auth/SessionProvider";
import { meOnServer } from "../lib/auth-server";
import {
  resolveDataTheme,
  resolveThemePreference,
  THEME_COOKIE_NAME,
} from "../lib/theme-cookie";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [cookieStore, initialUser] = await Promise.all([
    cookies(),
    meOnServer(),
  ]);
  const themeCookie = cookieStore.get(THEME_COOKIE_NAME)?.value;
  const dataTheme = resolveDataTheme(themeCookie);
  const initialThemePreference = resolveThemePreference(themeCookie);

  return (
    <html
      lang="en"
      data-theme={dataTheme}
      className={`${manrope.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="relative min-h-full">
        <div className="isolate flex min-h-full flex-col">
          <TooltipProvider>
            <SessionProvider initialUser={initialUser}>
              <AppShell initialThemePreference={initialThemePreference}>
                {children}
              </AppShell>
            </SessionProvider>
          </TooltipProvider>
        </div>
      </body>
    </html>
  );
}
