/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Turborepo Full Template API
 * REST API surface. All operations live under /v1.
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "./mutator";
export interface RefreshTokensDto {
  /** Refresh token (mobile clients without a cookie jar pass it in the body). Ignored when an `access_token` cookie is present and valid. */
  refreshToken?: string;
}

export interface TokenPairResponse {
  /** Signed access JWT. Also set as the `access_token` HttpOnly cookie; mobile clients consume the body field. */
  accessToken: string;
  /** Signed refresh JWT. Also set as the `refresh_token` HttpOnly cookie. */
  refreshToken: string;
}

export interface LogoutAllResponse {
  /** Number of sessions revoked, excluding the caller's current session. */
  sessionsRevoked: number;
}

export interface SessionUserResponse {
  id: string;
  email: string;
  /** @nullable */
  emailVerified: string | null;
  /** @nullable */
  phone: string | null;
  /** @nullable */
  phoneVerified: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  createdAt: string;
}

export interface SessionSummaryResponse {
  id: string;
  /** @nullable */
  userAgent: string | null;
  /** @nullable */
  ip: string | null;
  createdAt: string;
  lastUsedAt: string;
  /** True for the session whose refresh token issued the current request. */
  current: boolean;
}

export interface EnabledAuthMethodsResponse {
  emailOtp: boolean;
  smsOtp: boolean;
  credentials: boolean;
  google: boolean;
  facebook: boolean;
  apple: boolean;
}

/**
 * @nullable
 */
export type HealthControllerCheck200Info = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;

/**
 * @nullable
 */
export type HealthControllerCheck200Error = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;

export type HealthControllerCheck200Details = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
};

export type HealthControllerCheck200 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck200Info;
  /** @nullable */
  error?: HealthControllerCheck200Error;
  details?: HealthControllerCheck200Details;
};

/**
 * @nullable
 */
export type HealthControllerCheck503Info = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;

/**
 * @nullable
 */
export type HealthControllerCheck503Error = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
} | null;

export type HealthControllerCheck503Details = {
  [key: string]: {
    status: string;
    [key: string]: unknown;
  };
};

export type HealthControllerCheck503 = {
  status?: string;
  /** @nullable */
  info?: HealthControllerCheck503Info;
  /** @nullable */
  error?: HealthControllerCheck503Error;
  details?: HealthControllerCheck503Details;
};

/**
 * @summary Liveness + readiness probe
 */
export type healthControllerCheckResponse200 = {
  data: HealthControllerCheck200;
  status: 200;
};

export type healthControllerCheckResponse503 = {
  data: HealthControllerCheck503;
  status: 503;
};

export type healthControllerCheckResponseSuccess =
  healthControllerCheckResponse200 & {
    headers: Headers;
  };
export type healthControllerCheckResponseError =
  healthControllerCheckResponse503 & {
    headers: Headers;
  };

export type healthControllerCheckResponse =
  | healthControllerCheckResponseSuccess
  | healthControllerCheckResponseError;

export const getHealthControllerCheckUrl = () => {
  return `/healthz`;
};

export const healthControllerCheck = async (
  options?: RequestInit,
): Promise<healthControllerCheckResponse> => {
  return customFetch<healthControllerCheckResponse>(
    getHealthControllerCheckUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Rotate the refresh token (cookie or body)
 */
export type coreAuthControllerRefreshV1Response200 = {
  data: TokenPairResponse;
  status: 200;
};

export type coreAuthControllerRefreshV1ResponseSuccess =
  coreAuthControllerRefreshV1Response200 & {
    headers: Headers;
  };
export type coreAuthControllerRefreshV1Response =
  coreAuthControllerRefreshV1ResponseSuccess;

export const getCoreAuthControllerRefreshV1Url = () => {
  return `/v1/auth/refresh`;
};

export const coreAuthControllerRefreshV1 = async (
  refreshTokensDto: RefreshTokensDto,
  options?: RequestInit,
): Promise<coreAuthControllerRefreshV1Response> => {
  return customFetch<coreAuthControllerRefreshV1Response>(
    getCoreAuthControllerRefreshV1Url(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(refreshTokensDto),
    },
  );
};

/**
 * @summary Revoke the current session
 */
export type coreAuthControllerLogoutV1Response204 = {
  data: void;
  status: 204;
};

export type coreAuthControllerLogoutV1ResponseSuccess =
  coreAuthControllerLogoutV1Response204 & {
    headers: Headers;
  };
export type coreAuthControllerLogoutV1Response =
  coreAuthControllerLogoutV1ResponseSuccess;

export const getCoreAuthControllerLogoutV1Url = () => {
  return `/v1/auth/logout`;
};

export const coreAuthControllerLogoutV1 = async (
  options?: RequestInit,
): Promise<coreAuthControllerLogoutV1Response> => {
  return customFetch<coreAuthControllerLogoutV1Response>(
    getCoreAuthControllerLogoutV1Url(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Revoke every session of the current user (including this one)
 */
export type coreAuthControllerLogoutAllV1Response200 = {
  data: LogoutAllResponse;
  status: 200;
};

export type coreAuthControllerLogoutAllV1ResponseSuccess =
  coreAuthControllerLogoutAllV1Response200 & {
    headers: Headers;
  };
export type coreAuthControllerLogoutAllV1Response =
  coreAuthControllerLogoutAllV1ResponseSuccess;

export const getCoreAuthControllerLogoutAllV1Url = () => {
  return `/v1/auth/logout-all`;
};

export const coreAuthControllerLogoutAllV1 = async (
  options?: RequestInit,
): Promise<coreAuthControllerLogoutAllV1Response> => {
  return customFetch<coreAuthControllerLogoutAllV1Response>(
    getCoreAuthControllerLogoutAllV1Url(),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Current user profile
 */
export type coreAuthControllerMeV1Response200 = {
  data: SessionUserResponse;
  status: 200;
};

export type coreAuthControllerMeV1ResponseSuccess =
  coreAuthControllerMeV1Response200 & {
    headers: Headers;
  };
export type coreAuthControllerMeV1Response =
  coreAuthControllerMeV1ResponseSuccess;

export const getCoreAuthControllerMeV1Url = () => {
  return `/v1/auth/me`;
};

export const coreAuthControllerMeV1 = async (
  options?: RequestInit,
): Promise<coreAuthControllerMeV1Response> => {
  return customFetch<coreAuthControllerMeV1Response>(
    getCoreAuthControllerMeV1Url(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Hard-delete the current user. Cascades sessions, refresh tokens, OTPs, and OAuth links. Audit events survive.
 */
export type coreAuthControllerDeleteMeV1Response204 = {
  data: void;
  status: 204;
};

export type coreAuthControllerDeleteMeV1ResponseSuccess =
  coreAuthControllerDeleteMeV1Response204 & {
    headers: Headers;
  };
export type coreAuthControllerDeleteMeV1Response =
  coreAuthControllerDeleteMeV1ResponseSuccess;

export const getCoreAuthControllerDeleteMeV1Url = () => {
  return `/v1/auth/me`;
};

export const coreAuthControllerDeleteMeV1 = async (
  options?: RequestInit,
): Promise<coreAuthControllerDeleteMeV1Response> => {
  return customFetch<coreAuthControllerDeleteMeV1Response>(
    getCoreAuthControllerDeleteMeV1Url(),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List active sessions ('devices')
 */
export type coreAuthControllerListSessionsV1Response200 = {
  data: SessionSummaryResponse[];
  status: 200;
};

export type coreAuthControllerListSessionsV1ResponseSuccess =
  coreAuthControllerListSessionsV1Response200 & {
    headers: Headers;
  };
export type coreAuthControllerListSessionsV1Response =
  coreAuthControllerListSessionsV1ResponseSuccess;

export const getCoreAuthControllerListSessionsV1Url = () => {
  return `/v1/auth/sessions`;
};

export const coreAuthControllerListSessionsV1 = async (
  options?: RequestInit,
): Promise<coreAuthControllerListSessionsV1Response> => {
  return customFetch<coreAuthControllerListSessionsV1Response>(
    getCoreAuthControllerListSessionsV1Url(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Revoke one specific session
 */
export type coreAuthControllerRevokeSpecificSessionV1Response204 = {
  data: void;
  status: 204;
};

export type coreAuthControllerRevokeSpecificSessionV1ResponseSuccess =
  coreAuthControllerRevokeSpecificSessionV1Response204 & {
    headers: Headers;
  };
export type coreAuthControllerRevokeSpecificSessionV1Response =
  coreAuthControllerRevokeSpecificSessionV1ResponseSuccess;

export const getCoreAuthControllerRevokeSpecificSessionV1Url = (id: string) => {
  return `/v1/auth/sessions/${id}`;
};

export const coreAuthControllerRevokeSpecificSessionV1 = async (
  id: string,
  options?: RequestInit,
): Promise<coreAuthControllerRevokeSpecificSessionV1Response> => {
  return customFetch<coreAuthControllerRevokeSpecificSessionV1Response>(
    getCoreAuthControllerRevokeSpecificSessionV1Url(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Unlink an OAuth identity. Refuses if doing so would leave the user with no remaining auth method.
 */
export type coreAuthControllerUnlinkOAuthAccountV1Response204 = {
  data: void;
  status: 204;
};

export type coreAuthControllerUnlinkOAuthAccountV1ResponseSuccess =
  coreAuthControllerUnlinkOAuthAccountV1Response204 & {
    headers: Headers;
  };
export type coreAuthControllerUnlinkOAuthAccountV1Response =
  coreAuthControllerUnlinkOAuthAccountV1ResponseSuccess;

export const getCoreAuthControllerUnlinkOAuthAccountV1Url = (
  provider: string,
) => {
  return `/v1/auth/accounts/${provider}`;
};

export const coreAuthControllerUnlinkOAuthAccountV1 = async (
  provider: string,
  options?: RequestInit,
): Promise<coreAuthControllerUnlinkOAuthAccountV1Response> => {
  return customFetch<coreAuthControllerUnlinkOAuthAccountV1Response>(
    getCoreAuthControllerUnlinkOAuthAccountV1Url(provider),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Which auth methods this API has enabled. Drives conditional UI on the web/mobile clients.
 */
export type coreAuthControllerEnabledMethodsV1Response200 = {
  data: EnabledAuthMethodsResponse;
  status: 200;
};

export type coreAuthControllerEnabledMethodsV1ResponseSuccess =
  coreAuthControllerEnabledMethodsV1Response200 & {
    headers: Headers;
  };
export type coreAuthControllerEnabledMethodsV1Response =
  coreAuthControllerEnabledMethodsV1ResponseSuccess;

export const getCoreAuthControllerEnabledMethodsV1Url = () => {
  return `/v1/auth/enabled-methods`;
};

export const coreAuthControllerEnabledMethodsV1 = async (
  options?: RequestInit,
): Promise<coreAuthControllerEnabledMethodsV1Response> => {
  return customFetch<coreAuthControllerEnabledMethodsV1Response>(
    getCoreAuthControllerEnabledMethodsV1Url(),
    {
      ...options,
      method: "GET",
    },
  );
};
