#!/usr/bin/env tsx
/**
 * Walks `apps/api/src/config/env.ts`'s zod schema and writes a fully-
 * commented `apps/api/.env.example`. The schema's `.describe()` lines
 * become the `# comments`; defaults become the example values.
 *
 * Run via `pnpm gen:env`. Hooked into `pnpm gen`.
 *
 * Design choice: the schema is the single source of truth — there is no
 * separate `.env.example` to drift. Adding a new env var only requires
 * extending the zod schema with a `.describe()`; `.env.example` regenerates.
 *
 * Implementation: uses `z.toJSONSchema()` (Zod 4) to produce a stable
 * JSON-Schema view of the env schema, then iterates `properties` and the
 * top-level `required` array. We deliberately avoid poking at Zod 4's
 * internal `_zod.def` — those internals are explicitly marked unstable.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

import { envSchema } from "../apps/api/src/config/env";

interface FieldSchema {
  description?: string;
  default?: unknown;
  // Other fields from JSONSchema (type, format, enum, etc.) are present
  // but the env-example only needs description + default.
}

interface JsonSchemaShape {
  properties?: Record<string, FieldSchema>;
  required?: string[];
}

function exampleFor(value: unknown): string {
  if (value === undefined) return "";
  if (Array.isArray(value)) return value.join(",");
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return value;
  return "";
}

function lineFor(key: string, field: FieldSchema, required: boolean): string[] {
  const out: string[] = [];
  if (field.description) {
    for (const paragraph of field.description.split("\n")) {
      const words = paragraph.trim().split(/\s+/);
      let line = "#";
      for (const word of words) {
        if (line.length + word.length + 1 > 80) {
          out.push(line);
          line = "#";
        }
        line += ` ${word}`;
      }
      out.push(line);
    }
  }
  out.push(
    `# Required: ${required && field.default === undefined ? "yes" : "no"}`,
  );
  if (field.default !== undefined) {
    out.push(`# Default: ${exampleFor(field.default) || '""'}`);
  }
  out.push(`${key}=${exampleFor(field.default)}`);
  return out;
}

function generate(): string {
  // `z.toJSONSchema` produces a stable JSON Schema view. `unrepresentable:
  // "any"` keeps transforms (e.g. CORS_ORIGINS' string→string[] transform)
  // from throwing — we don't need the post-transform type, just description
  // and default.
  const json = z.toJSONSchema(envSchema, {
    unrepresentable: "any",
  }) as JsonSchemaShape;

  if (!json.properties) {
    throw new Error(
      "Expected envSchema to produce JSON Schema with properties",
    );
  }
  const requiredSet = new Set(json.required ?? []);

  const blocks: string[] = [
    "# ==========================================================================",
    "# Auto-generated by `pnpm gen:env`. DO NOT EDIT BY HAND.",
    "# Source of truth: apps/api/src/config/env.ts",
    "# ==========================================================================",
    "",
  ];

  blocks.push(
    "# Grouped by feature; switches sit beside their settings and credentials.",
    "# Values below are schema defaults. Blank values have no schema default.",
    "# Optional providers may require credentials when enabled; see descriptions.",
    "",
  );
  const sections: Array<[string, RegExp]> = [
    [
      "Application and HTTP",
      /^(NODE_ENV|PORT|APP_BASE_URL|API_BASE_URL|HEALTH_MAX_HEAP_MB|COOKIE_DOMAIN|CORS_ORIGINS)$/,
    ],
    ["Database", /^DATABASE_/],
    ["Image and document storage", /^IMAGE_STORAGE_/],
    ["AWS credentials", /^AWS_/],
    ["Receipt extraction", /^DOCUMENT_EXTRACTION_/],
    ["Person document extraction", /^PERSON_DOCUMENT_EXTRACTION_/],
    [
      "Sessions and signing keys",
      /^(JWT_|REFRESH_TOKEN_|ROTATION_|AUTH_CLEANUP_)/,
    ],
    ["Email OTP", /^(AUTH_EMAIL_OTP_|OTP_)/],
    ["Google sign-in", /^(AUTH_GOOGLE_|GOOGLE_)/],
    ["Apple sign-in", /^(AUTH_APPLE_|APPLE_)/],
    ["Email delivery", /^(MAILER_|SMTP_)/],
    ["SMS delivery", /^(SMS_|SMSO_)/],
    ["Request limits", /^THROTTLE_/],
    ["Other settings", /./],
  ];
  const remaining = new Map(Object.entries(json.properties));
  for (const [title, pattern] of sections) {
    const entries = [...remaining].filter(([key]) => pattern.test(key));
    if (!entries.length) continue;
    blocks.push(
      `# --- ${title} ${"-".repeat(Math.max(0, 68 - title.length))}`,
      "",
    );
    for (const [key, field] of entries) {
      blocks.push(...lineFor(key, field, requiredSet.has(key)), "");
      remaining.delete(key);
    }
  }

  return blocks.join("\n");
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const target = resolve(here, "..", "apps", "api", ".env.example");
  const content = generate();
  writeFileSync(target, content, "utf8");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${target}`);
}

main();
