#!/usr/bin/env tsx
/**
 * Walks `apps/api/src/config/env.ts`'s zod schema and writes a fully-
 * commented `apps/api/.env.example`. The schema's `.describe()` lines
 * become the `# comments`; defaults become the example values.
 *
 * Run via `pnpm gen:env`. Hooked into `pnpm gen`.
 *
 * Design choice: the schema is the single source of truth — there is no
 * separate `.env.example` to drift. Adding a new env var only requires
 * extending the zod schema with a `.describe()`; `.env.example` regenerates.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  z,
  ZodDefault,
  ZodEffects,
  ZodObject,
  ZodOptional,
  ZodTypeAny,
} from "zod";

import { envSchema } from "../apps/api/src/config/env";

type ZodShape = Record<string, ZodTypeAny>;

function unwrap(schema: ZodTypeAny): {
  inner: ZodTypeAny;
  optional: boolean;
  defaultValue: unknown;
  description: string | undefined;
} {
  let cur: ZodTypeAny = schema;
  let optional = false;
  let defaultValue: unknown;
  let description: string | undefined;

  // ZodEffects wraps refines/transforms; recurse into inner schema.
  while (cur instanceof ZodEffects) {
    cur = cur._def.schema as ZodTypeAny;
  }
  if (description === undefined && cur.description)
    description = cur.description;

  if (cur instanceof ZodDefault) {
    defaultValue = cur._def.defaultValue();
    cur = cur._def.innerType as ZodTypeAny;
  }
  if (cur instanceof ZodOptional) {
    optional = true;
    cur = cur._def.innerType as ZodTypeAny;
  }
  if (cur instanceof ZodDefault) {
    defaultValue = cur._def.defaultValue();
    cur = cur._def.innerType as ZodTypeAny;
  }
  if (description === undefined && cur.description)
    description = cur.description;
  // Also check the original schema's description (it might be on the wrapper).
  if (description === undefined && schema.description)
    description = schema.description;

  return { inner: cur, optional, defaultValue, description };
}

function exampleFor(value: unknown, optional: boolean): string {
  if (value === undefined) return "";
  if (Array.isArray(value)) return value.join(",");
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return value;
  return optional ? "" : "";
}

function lineFor(key: string, schema: ZodTypeAny): string[] {
  const { optional, defaultValue, description } = unwrap(schema);
  const out: string[] = [];
  if (description) {
    out.push(...description.split("\n").map((s) => `# ${s.trim()}`));
  }
  out.push(
    `# Required: ${optional || defaultValue !== undefined ? "no" : "yes"}`,
  );
  if (defaultValue !== undefined) {
    out.push(`# Default: ${exampleFor(defaultValue, false) || '""'}`);
  }
  const example = exampleFor(defaultValue, optional);
  out.push(`${key}=${example}`);
  return out;
}

function generate(): string {
  // The schema is wrapped in `.superRefine(...)` which produces a ZodEffects.
  // Unwrap to reach the underlying ZodObject so we can iterate `.shape`.
  let inner: ZodTypeAny = envSchema as ZodTypeAny;
  while (inner instanceof ZodEffects) {
    inner = inner._def.schema as ZodTypeAny;
  }
  if (!(inner instanceof ZodObject)) {
    throw new Error("Expected envSchema to resolve to a ZodObject");
  }
  const shape = inner.shape as ZodShape;

  const blocks: string[] = [
    "# ==========================================================================",
    "# Auto-generated by `pnpm gen:env`. DO NOT EDIT BY HAND.",
    "# Source of truth: apps/api/src/config/env.ts",
    "# ==========================================================================",
    "",
  ];

  for (const [key, subSchema] of Object.entries(shape)) {
    blocks.push(...lineFor(key, subSchema), "");
  }

  return blocks.join("\n");
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const target = resolve(here, "..", "apps", "api", ".env.example");
  const content = generate();
  writeFileSync(target, content, "utf8");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${target}`);
}

// Silence "z is unused" linter complaint — re-exporting for completeness in case
// scripts/ later imports a custom-typed helper.
void z;

main();
