#!/usr/bin/env tsx
/**
 * Walks `apps/api/src/config/env.ts`'s zod schema and writes a fully-
 * commented `apps/api/.env.example`. The schema's `.describe()` lines
 * become the `# comments`; defaults become the example values.
 *
 * Run via `pnpm gen:env`. Hooked into `pnpm gen`.
 *
 * Design choice: the schema is the single source of truth — there is no
 * separate `.env.example` to drift. Adding a new env var only requires
 * extending the zod schema with a `.describe()`; `.env.example` regenerates.
 *
 * Implementation: uses `z.toJSONSchema()` (Zod 4) to produce a stable
 * JSON-Schema view of the env schema, then iterates `properties` and the
 * top-level `required` array. We deliberately avoid poking at Zod 4's
 * internal `_zod.def` — those internals are explicitly marked unstable.
 */
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";

import { envSchema } from "../apps/api/src/config/env";

interface FieldSchema {
  description?: string;
  default?: unknown;
  // Other fields from JSONSchema (type, format, enum, etc.) are present
  // but the env-example only needs description + default.
}

interface JsonSchemaShape {
  properties?: Record<string, FieldSchema>;
  required?: string[];
}

function exampleFor(value: unknown): string {
  if (value === undefined) return "";
  if (Array.isArray(value)) return value.join(",");
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") return value;
  return "";
}

function lineFor(key: string, field: FieldSchema, required: boolean): string[] {
  const out: string[] = [];
  if (field.description) {
    out.push(...field.description.split("\n").map((s) => `# ${s.trim()}`));
  }
  out.push(
    `# Required: ${required && field.default === undefined ? "yes" : "no"}`,
  );
  if (field.default !== undefined) {
    out.push(`# Default: ${exampleFor(field.default) || '""'}`);
  }
  out.push(`${key}=${exampleFor(field.default)}`);
  return out;
}

function generate(): string {
  // `z.toJSONSchema` produces a stable JSON Schema view. `unrepresentable:
  // "any"` keeps transforms (e.g. CORS_ORIGINS' string→string[] transform)
  // from throwing — we don't need the post-transform type, just description
  // and default.
  const json = z.toJSONSchema(envSchema, {
    unrepresentable: "any",
  }) as JsonSchemaShape;

  if (!json.properties) {
    throw new Error(
      "Expected envSchema to produce JSON Schema with properties",
    );
  }
  const requiredSet = new Set(json.required ?? []);

  const blocks: string[] = [
    "# ==========================================================================",
    "# Auto-generated by `pnpm gen:env`. DO NOT EDIT BY HAND.",
    "# Source of truth: apps/api/src/config/env.ts",
    "# ==========================================================================",
    "",
  ];

  for (const [key, field] of Object.entries(json.properties)) {
    blocks.push(...lineFor(key, field, requiredSet.has(key)), "");
  }

  return blocks.join("\n");
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const target = resolve(here, "..", "apps", "api", ".env.example");
  const content = generate();
  writeFileSync(target, content, "utf8");
  // eslint-disable-next-line no-console
  console.log(`Wrote ${target}`);
}

main();
