/**
 * Generates platform outputs from the TS token source.
 *
 *   generated/tokens.css       — Tailwind v4 @theme block + dark-mode CSS var overrides
 *   generated/tokens.native.ts — Single JS object consumed by @repo/theme-native
 *
 * Both files are committed so consumers don't need to run a build before `dev`.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { primitives } from "../src/tokens/primitives.js";
import { semanticColors } from "../src/tokens/semantic.js";
import { spacing } from "../src/tokens/spacing.js";
import { radius } from "../src/tokens/radius.js";
import { typography } from "../src/tokens/typography.js";
import { shadow } from "../src/tokens/shadow.js";
import { motion } from "../src/tokens/motion.js";
import { zIndex } from "../src/tokens/z-index.js";
import { breakpoints } from "../src/tokens/breakpoints.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, "../generated");

const BANNER = `/* GENERATED by scripts/build-tokens.ts — DO NOT EDIT. */`;

// ---------- helpers ----------

const pxToRem = (px: number) => (px === 0 ? "0" : `${px / 16}rem`);

const kebab = (s: string | number) =>
  String(s)
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/[._]/g, "-")
    .toLowerCase();

const flattenColors = (
  obj: Record<string, Record<string, string>>,
  prefix: string,
): Array<[string, string]> => {
  const out: Array<[string, string]> = [];
  for (const [group, scale] of Object.entries(obj)) {
    for (const [key, value] of Object.entries(scale)) {
      out.push([`${prefix}-${kebab(group)}-${kebab(key)}`, value]);
    }
  }
  return out;
};

// ---------- CSS output ----------

function buildCss(): string {
  const lines: string[] = [BANNER, ""];

  // @theme block — registers utility classes for all tokens. Light values are the default.
  lines.push("@theme {");

  // Primitive colors → --color-neutral-50, --color-blue-600, etc.
  for (const [name, value] of flattenColors(primitives, "--color")) {
    lines.push(`  ${name}: ${value};`);
  }

  lines.push("");
  // Semantic colors (light default) → --color-surface-page, --color-text-primary, etc.
  for (const [group, scale] of Object.entries(semanticColors.light)) {
    for (const [key, value] of Object.entries(scale)) {
      lines.push(`  --color-${kebab(group)}-${kebab(key)}: ${value};`);
    }
  }

  lines.push("");
  // Spacing → --spacing-1, --spacing-4, etc.
  for (const [key, value] of Object.entries(spacing)) {
    lines.push(`  --spacing-${kebab(key)}: ${pxToRem(value)};`);
  }

  lines.push("");
  // Radius
  for (const [key, value] of Object.entries(radius)) {
    lines.push(
      `  --radius-${kebab(key)}: ${value >= 9999 ? "9999px" : pxToRem(value)};`,
    );
  }

  lines.push("");
  // Font family (web variant)
  for (const [key, value] of Object.entries(typography.fontFamily)) {
    lines.push(`  --font-${kebab(key)}: ${value.web};`);
  }

  lines.push("");
  // Font size
  for (const [key, value] of Object.entries(typography.fontSize)) {
    lines.push(`  --text-${kebab(key)}: ${pxToRem(value)};`);
  }

  lines.push("");
  // Font weight
  for (const [key, value] of Object.entries(typography.fontWeight)) {
    lines.push(`  --font-weight-${kebab(key)}: ${value};`);
  }

  lines.push("");
  // Line height (unitless)
  for (const [key, value] of Object.entries(typography.lineHeight)) {
    lines.push(`  --leading-${kebab(key)}: ${value};`);
  }

  lines.push("");
  // Letter spacing
  for (const [key, value] of Object.entries(typography.letterSpacing)) {
    lines.push(
      `  --tracking-${kebab(key)}: ${value === 0 ? "0" : `${value / 16}rem`};`,
    );
  }

  lines.push("");
  // Shadow (web variant)
  for (const [key, value] of Object.entries(shadow)) {
    lines.push(`  --shadow-${kebab(key)}: ${value.web};`);
  }

  lines.push("");
  // Motion
  for (const [key, value] of Object.entries(motion.duration)) {
    lines.push(`  --duration-${kebab(key)}: ${value}ms;`);
  }
  for (const [key, value] of Object.entries(motion.easing)) {
    lines.push(`  --ease-${kebab(key)}: ${value};`);
  }

  lines.push("");
  // Z-index
  for (const [key, value] of Object.entries(zIndex)) {
    lines.push(`  --z-${kebab(key)}: ${value};`);
  }

  lines.push("");
  // Breakpoints → --breakpoint-md drives `md:` variants in Tailwind v4
  for (const [key, value] of Object.entries(breakpoints)) {
    lines.push(`  --breakpoint-${kebab(key)}: ${value}px;`);
  }

  lines.push("}", "");

  // Dark-mode override — replaces semantic color vars at runtime.
  // Triggers: system preference (unless user explicitly chose light), or [data-theme="dark"].
  const darkVarLines: string[] = [];
  for (const [group, scale] of Object.entries(semanticColors.dark)) {
    for (const [key, value] of Object.entries(scale)) {
      darkVarLines.push(`--color-${kebab(group)}-${kebab(key)}: ${value};`);
    }
  }

  lines.push("@media (prefers-color-scheme: dark) {");
  lines.push("  :root:not([data-theme='light']) {");
  for (const v of darkVarLines) lines.push(`    ${v}`);
  lines.push("  }");
  lines.push("}", "");

  lines.push(":root[data-theme='dark'] {");
  for (const v of darkVarLines) lines.push(`  ${v}`);
  lines.push("}", "");

  return lines.join("\n");
}

// ---------- native output ----------

function buildNative(): string {
  // Build a single typed JS object. Spacing/radius stay as numbers (RN expects dp).
  const out = {
    primitives,
    color: semanticColors,
    spacing,
    radius,
    typography: {
      fontFamily: Object.fromEntries(
        Object.entries(typography.fontFamily).map(([k, v]) => [k, v.native]),
      ),
      fontSize: typography.fontSize,
      lineHeight: typography.lineHeight,
      fontWeight: typography.fontWeight,
      letterSpacing: typography.letterSpacing,
    },
    shadow: Object.fromEntries(
      Object.entries(shadow).map(([k, v]) => [k, v.native]),
    ),
    motion,
    zIndex,
    breakpoints,
  };

  const body = JSON.stringify(out, null, 2);

  return `${BANNER}

export const tokens = ${body} as const;

export type Tokens = typeof tokens;
export type ColorScheme = "light" | "dark";
`;
}

// ---------- write ----------

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(resolve(OUT_DIR, "tokens.css"), buildCss(), "utf8");
  await writeFile(resolve(OUT_DIR, "tokens.native.ts"), buildNative(), "utf8");
  console.log(`[theme] wrote ${OUT_DIR}/tokens.css`);
  console.log(`[theme] wrote ${OUT_DIR}/tokens.native.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
