/**
 * Generates platform outputs from the canonical TypeScript token source.
 */
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import { formatHex, formatHex8, parse, toGamut } from "culori";

import { breakpoints } from "../src/tokens/breakpoints.js";
import { motion } from "../src/tokens/motion.js";
import { primitives } from "../src/tokens/primitives.js";
import { radius, radiusBase } from "../src/tokens/radius.js";
import { semanticColors } from "../src/tokens/semantic.js";
import { shadow } from "../src/tokens/shadow.js";
import { spacing } from "../src/tokens/spacing.js";
import { typography } from "../src/tokens/typography.js";
import { zIndex } from "../src/tokens/z-index.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, "../generated");
const BANNER = "/* GENERATED by scripts/build-tokens.ts — DO NOT EDIT. */";
const toSrgbGamut = toGamut("rgb", "oklch");

const pxToRem = (px: number) => (px === 0 ? "0" : `${px / 16}rem`);

const kebab = (value: string | number) =>
  String(value)
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .replace(/([A-Za-z])(\d)/g, "$1-$2")
    .replace(/[._]/g, "-")
    .toLowerCase();

const flattenColors = (
  value: Record<string, Record<string, string>>,
  prefix: string,
): Array<[string, string]> =>
  Object.entries(value).flatMap(([group, scale]) =>
    Object.entries(scale).map(
      ([key, color]) =>
        [`${prefix}-${kebab(group)}-${kebab(key)}`, color] as [string, string],
    ),
  );

const assertColorContract = () => {
  const lightKeys = Object.keys(semanticColors.light).sort();
  const darkKeys = Object.keys(semanticColors.dark).sort();

  if (lightKeys.join("|") !== darkKeys.join("|")) {
    throw new Error("Light and dark semantic color keys must match.");
  }

  for (const [scheme, colors] of Object.entries(semanticColors)) {
    for (const [name, value] of Object.entries(colors)) {
      if (!parse(value)) {
        throw new Error(`Invalid ${scheme} color "${name}": ${value}`);
      }
    }
  }
};

const nativeColor = (value: string): string => {
  const parsed = parse(value);
  if (!parsed) throw new Error(`Invalid color: ${value}`);

  const converted = toSrgbGamut(parsed);
  const formatted =
    converted?.alpha !== undefined && converted.alpha < 1
      ? formatHex8(converted)
      : formatHex(converted);

  if (!formatted) throw new Error(`Could not convert color: ${value}`);
  return formatted.toUpperCase();
};

const nativeColorObject = <T extends Record<string, string>>(value: T) =>
  Object.fromEntries(
    Object.entries(value).map(([key, color]) => [key, nativeColor(color)]),
  ) as Record<keyof T, string>;

const cssColorLines = (colors: Record<string, string>, indent: string) =>
  Object.entries(colors).map(
    ([name, value]) => `${indent}--${kebab(name)}: ${value};`,
  );

export function buildCss(): string {
  assertColorContract();
  const lines: string[] = [BANNER, "", ":root {"];
  lines.push(`  --radius: ${pxToRem(radiusBase)};`);
  lines.push(...cssColorLines(semanticColors.light, "  "));
  lines.push("}", "");

  const darkLines = cssColorLines(semanticColors.dark, "    ");
  lines.push("@media (prefers-color-scheme: dark) {");
  lines.push("  :root:not([data-theme='light']) {");
  lines.push(...darkLines);
  lines.push("  }");
  lines.push("}", "");
  lines.push(":root[data-theme='dark'], .dark {");
  lines.push(...cssColorLines(semanticColors.dark, "  "));
  lines.push("}", "");

  lines.push("@theme {");
  for (const [name, value] of flattenColors(primitives, "--color")) {
    lines.push(`  ${name}: ${value};`);
  }
  lines.push("");
  for (const [key, value] of Object.entries(spacing)) {
    lines.push(`  --spacing-${kebab(key)}: ${pxToRem(value)};`);
  }
  lines.push("");
  for (const [key, value] of Object.entries(typography.fontSize)) {
    lines.push(`  --text-${kebab(key)}: ${pxToRem(value)};`);
  }
  for (const [key, value] of Object.entries(typography.fontWeight)) {
    lines.push(`  --font-weight-${kebab(key)}: ${value};`);
  }
  for (const [key, value] of Object.entries(typography.lineHeight)) {
    lines.push(`  --leading-${kebab(key)}: ${value};`);
  }
  for (const [key, value] of Object.entries(typography.letterSpacing)) {
    lines.push(
      `  --tracking-${kebab(key)}: ${value === 0 ? "0" : pxToRem(value)};`,
    );
  }
  lines.push("");
  for (const [key, value] of Object.entries(shadow)) {
    lines.push(`  --shadow-${kebab(key)}: ${value.web};`);
  }
  lines.push("");
  for (const [key, value] of Object.entries(motion.duration)) {
    lines.push(`  --duration-${kebab(key)}: ${value}ms;`);
  }
  for (const [key, value] of Object.entries(motion.easing)) {
    lines.push(`  --ease-${kebab(key)}: ${value};`);
  }
  lines.push("");
  for (const [key, value] of Object.entries(zIndex)) {
    lines.push(`  --z-${kebab(key)}: ${value};`);
  }
  lines.push("");
  for (const [key, value] of Object.entries(breakpoints)) {
    lines.push(`  --breakpoint-${kebab(key)}: ${value}px;`);
  }
  lines.push("}", "");

  lines.push("@theme inline {");
  for (const name of Object.keys(semanticColors.light)) {
    lines.push(`  --color-${kebab(name)}: var(--${kebab(name)});`);
  }
  lines.push("");
  lines.push("  --radius-none: 0;");
  lines.push("  --radius-sm: max(0px, calc(var(--radius) - 4px));");
  lines.push("  --radius-md: max(0px, calc(var(--radius) - 2px));");
  lines.push("  --radius-lg: var(--radius);");
  lines.push("  --radius-xl: calc(var(--radius) + 4px);");
  lines.push("  --radius-2xl: calc(var(--radius) + 8px);");
  lines.push("  --radius-3xl: calc(var(--radius) + 12px);");
  lines.push("  --radius-4xl: calc(var(--radius) + 16px);");
  lines.push("  --radius-full: 9999px;");
  lines.push("");
  for (const [key, value] of Object.entries(typography.fontFamily)) {
    lines.push(`  --font-${kebab(key)}: ${value.web};`);
  }
  lines.push("}", "");

  for (const key of Object.keys(zIndex)) {
    const name = kebab(key);
    lines.push(`@utility z-${name} {`);
    lines.push(`  z-index: var(--z-${name});`);
    lines.push("}", "");
  }

  return lines.join("\n");
}

export function buildNative(): string {
  assertColorContract();
  const output = {
    color: {
      light: nativeColorObject(semanticColors.light),
      dark: nativeColorObject(semanticColors.dark),
    },
    spacing,
    radius,
    typography: {
      fontFamily: Object.fromEntries(
        Object.entries(typography.fontFamily).map(([key, value]) => [
          key,
          value.native,
        ]),
      ),
      fontFamilyByWeight: typography.fontFamilyByWeight,
      fontSize: typography.fontSize,
      lineHeight: typography.lineHeight,
      fontWeight: typography.fontWeight,
      letterSpacing: typography.letterSpacing,
    },
    shadow: Object.fromEntries(
      Object.entries(shadow).map(([key, value]) => [
        key,
        {
          ...value.native,
          shadowColor: nativeColor(value.native.shadowColor),
        },
      ]),
    ),
    motion,
    zIndex,
    breakpoints,
  };

  return `${BANNER}

export const tokens = ${JSON.stringify(output, null, 2)} as const;

export type Tokens = typeof tokens;
export type ColorScheme = "light" | "dark";
`;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(resolve(OUT_DIR, "tokens.css"), buildCss(), "utf8");
  await writeFile(resolve(OUT_DIR, "tokens.native.ts"), buildNative(), "utf8");
  console.log(`[theme] wrote ${OUT_DIR}/tokens.css`);
  console.log(`[theme] wrote ${OUT_DIR}/tokens.native.ts`);
}

const entrypoint = process.argv[1]
  ? pathToFileURL(resolve(process.argv[1])).href
  : undefined;

if (entrypoint === import.meta.url) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
