import { primitives as p } from "./primitives";

const light = {
  background: p.mist[100],
  foreground: p.charcoal[950],
  card: p.mist[0],
  cardForeground: p.charcoal[950],
  popover: p.mist[0],
  popoverForeground: p.charcoal[950],
  primary: p.cyan[500],
  primaryForeground: p.charcoal[950],
  secondary: p.mist[100],
  secondaryForeground: p.mist[900],
  muted: p.mist[100],
  mutedForeground: p.mist[600],
  accent: p.cyan[50],
  accentForeground: p.cyan[900],
  destructive: p.red[600],
  destructiveForeground: p.mist[50],
  border: p.mist[200],
  input: p.mist[200],
  ring: p.cyan[700],
  chart1: p.cyan[600],
  chart2: p.charcoal[600],
  chart3: p.cyan[800],
  chart4: p.charcoal[500],
  chart5: p.charcoal[800],
  sidebar: p.charcoal[950],
  sidebarForeground: p.charcoal[50],
  sidebarMutedForeground: p.charcoal[300],
  sidebarPrimary: p.cyan[500],
  sidebarPrimaryForeground: p.charcoal[950],
  sidebarAccent: p.charcoal[800],
  sidebarAccentForeground: p.charcoal[50],
  sidebarBorder: p.charcoal[800],
  sidebarRing: p.cyan[500],
  primaryHover: p.cyan[550],
  primaryActive: p.cyan[600],
  secondaryHover: p.mist[200],
  secondaryActive: p.mist[300],
  accentHover: p.cyan[100],
  accentActive: p.cyan[200],
  destructiveHover: p.red[700],
  destructiveActive: p.red[800],
  destructiveSubtle: p.red[50],
  success: p.green[700],
  successForeground: p.mist[50],
  successHover: p.green[800],
  successActive: p.green[900],
  successSubtle: p.green[50],
  warning: p.amber[600],
  warningForeground: p.mist[950],
  warningHover: p.amber[700],
  warningActive: p.amber[800],
  warningSubtle: p.amber[50],
  info: p.blue[600],
  infoForeground: p.mist[50],
  infoHover: p.blue[700],
  infoActive: p.blue[800],
  infoSubtle: p.blue[50],
  disabled: p.mist[100],
  disabledForeground: p.mist[400],
  link: p.cyan[700],
  linkHover: p.cyan[800],
  linkActive: p.cyan[900],
  borderStrong: p.mist[400],
  scrim: "oklch(0 0 0 / 40%)",
  scrimForeground: p.mist[50],
  mediaScrim: "oklch(0 0 0 / 65%)",
} as const;

const dark: Record<keyof typeof light, string> = {
  background: p.charcoal[1000],
  foreground: p.mist[50],
  card: p.charcoal[950],
  cardForeground: p.mist[50],
  popover: p.charcoal[900],
  popoverForeground: p.mist[50],
  primary: p.cyan[500],
  primaryForeground: p.charcoal[950],
  secondary: p.mist[800],
  secondaryForeground: p.mist[50],
  muted: p.mist[800],
  mutedForeground: p.mist[400],
  accent: p.cyan[950],
  accentForeground: p.cyan[100],
  destructive: p.red[400],
  destructiveForeground: p.mist[950],
  border: "oklch(1 0 0 / 10%)",
  input: "oklch(1 0 0 / 15%)",
  ring: p.cyan[500],
  chart1: p.cyan[500],
  chart2: p.charcoal[300],
  chart3: p.cyan[200],
  chart4: p.charcoal[500],
  chart5: p.cyan[600],
  sidebar: p.charcoal[950],
  sidebarForeground: p.charcoal[50],
  sidebarMutedForeground: p.charcoal[300],
  sidebarPrimary: p.cyan[500],
  sidebarPrimaryForeground: p.charcoal[950],
  sidebarAccent: p.charcoal[800],
  sidebarAccentForeground: p.charcoal[50],
  sidebarBorder: p.charcoal[800],
  sidebarRing: p.cyan[500],
  primaryHover: p.cyan[550],
  primaryActive: p.cyan[600],
  secondaryHover: p.mist[700],
  secondaryActive: p.mist[600],
  accentHover: p.cyan[900],
  accentActive: p.cyan[800],
  destructiveHover: p.red[500],
  destructiveActive: p.red[600],
  destructiveSubtle: p.red[950],
  success: p.green[500],
  successForeground: p.mist[950],
  successHover: p.green[600],
  successActive: p.green[700],
  successSubtle: p.green[950],
  warning: p.amber[500],
  warningForeground: p.mist[950],
  warningHover: p.amber[600],
  warningActive: p.amber[700],
  warningSubtle: p.amber[950],
  info: p.blue[400],
  infoForeground: p.mist[950],
  infoHover: p.blue[500],
  infoActive: p.blue[600],
  infoSubtle: p.blue[950],
  disabled: p.mist[800],
  disabledForeground: p.mist[600],
  link: p.cyan[500],
  linkHover: p.cyan[300],
  linkActive: p.cyan[200],
  borderStrong: p.mist[600],
  scrim: "oklch(0 0 0 / 65%)",
  scrimForeground: p.mist[50],
  mediaScrim: "oklch(0 0 0 / 65%)",
};

const minimal: Record<keyof typeof light, string> = {
  ...dark,
  card: dark.background,
};

export const semanticColors = { light, dark, minimal } as const;

export type ThemeColors = typeof light;
