import { primitives as p } from "./primitives";

const light = {
  background: p.mist[0],
  foreground: p.mist[950],
  card: p.mist[0],
  cardForeground: p.mist[950],
  popover: p.mist[0],
  popoverForeground: p.mist[950],
  primary: p.mist[900],
  primaryForeground: p.mist[50],
  secondary: p.mist[100],
  secondaryForeground: p.mist[900],
  muted: p.mist[100],
  mutedForeground: p.mist[500],
  accent: p.mist[100],
  accentForeground: p.mist[900],
  destructive: p.red[600],
  destructiveForeground: p.mist[50],
  border: p.mist[200],
  input: p.mist[200],
  ring: p.mist[400],
  chart1: p.mist[300],
  chart2: p.mist[500],
  chart3: p.mist[600],
  chart4: p.mist[700],
  chart5: p.mist[800],
  sidebar: p.mist[50],
  sidebarForeground: p.mist[950],
  sidebarPrimary: p.mist[900],
  sidebarPrimaryForeground: p.mist[50],
  sidebarAccent: p.mist[100],
  sidebarAccentForeground: p.mist[900],
  sidebarBorder: p.mist[200],
  sidebarRing: p.mist[400],
  primaryHover: p.mist[800],
  primaryActive: p.mist[950],
  secondaryHover: p.mist[200],
  secondaryActive: p.mist[300],
  accentHover: p.mist[200],
  accentActive: p.mist[300],
  destructiveHover: p.red[700],
  destructiveActive: p.red[800],
  destructiveSubtle: p.red[50],
  success: p.green[700],
  successForeground: p.mist[50],
  successHover: p.green[800],
  successActive: p.green[900],
  successSubtle: p.green[50],
  warning: p.amber[600],
  warningForeground: p.mist[950],
  warningHover: p.amber[700],
  warningActive: p.amber[800],
  warningSubtle: p.amber[50],
  info: p.blue[600],
  infoForeground: p.mist[50],
  infoHover: p.blue[700],
  infoActive: p.blue[800],
  infoSubtle: p.blue[50],
  disabled: p.mist[100],
  disabledForeground: p.mist[400],
  link: p.blue[600],
  linkHover: p.blue[700],
  linkActive: p.blue[800],
  borderStrong: p.mist[400],
  scrim: "oklch(0 0 0 / 40%)",
} as const;

const dark: Record<keyof typeof light, string> = {
  background: p.mist[950],
  foreground: p.mist[50],
  card: p.mist[900],
  cardForeground: p.mist[50],
  popover: p.mist[900],
  popoverForeground: p.mist[50],
  primary: p.mist[200],
  primaryForeground: p.mist[900],
  secondary: p.mist[800],
  secondaryForeground: p.mist[50],
  muted: p.mist[800],
  mutedForeground: p.mist[400],
  accent: p.mist[800],
  accentForeground: p.mist[50],
  destructive: p.red[400],
  destructiveForeground: p.mist[950],
  border: "oklch(1 0 0 / 10%)",
  input: "oklch(1 0 0 / 15%)",
  ring: p.mist[500],
  chart1: p.mist[300],
  chart2: p.mist[500],
  chart3: p.mist[600],
  chart4: p.mist[700],
  chart5: p.mist[800],
  sidebar: p.mist[900],
  sidebarForeground: p.mist[50],
  sidebarPrimary: p.blue[700],
  sidebarPrimaryForeground: p.mist[50],
  sidebarAccent: p.mist[800],
  sidebarAccentForeground: p.mist[50],
  sidebarBorder: "oklch(1 0 0 / 10%)",
  sidebarRing: p.mist[500],
  primaryHover: p.mist[300],
  primaryActive: p.mist[400],
  secondaryHover: p.mist[700],
  secondaryActive: p.mist[600],
  accentHover: p.mist[700],
  accentActive: p.mist[600],
  destructiveHover: p.red[500],
  destructiveActive: p.red[600],
  destructiveSubtle: p.red[950],
  success: p.green[500],
  successForeground: p.mist[950],
  successHover: p.green[600],
  successActive: p.green[700],
  successSubtle: p.green[950],
  warning: p.amber[500],
  warningForeground: p.mist[950],
  warningHover: p.amber[600],
  warningActive: p.amber[700],
  warningSubtle: p.amber[950],
  info: p.blue[400],
  infoForeground: p.mist[950],
  infoHover: p.blue[500],
  infoActive: p.blue[600],
  infoSubtle: p.blue[950],
  disabled: p.mist[800],
  disabledForeground: p.mist[600],
  link: p.blue[400],
  linkHover: p.blue[300],
  linkActive: p.blue[200],
  borderStrong: p.mist[600],
  scrim: "oklch(0 0 0 / 65%)",
};

export const semanticColors = { light, dark } as const;

export type ThemeColors = typeof light;
